{{- if .Values.frontendConfigEnabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Values.frontendConfig.name }}
spec:
  {{- if .Values.frontendConfig.redirectToHttps.enabled }}
  redirectToHttps:
    enabled: {{ .Values.frontendConfig.redirectToHttps.enabled }}
    responseCodeName: {{ .Values.frontendConfig.redirectToHttps.responseCodeName }}
  {{- end }}  
  {{- if .Values.frontendConfig.sslPolicy }}
  sslPolicy: {{ .Values.frontendConfig.sslPolicy }}
  {{- end }}
{{- end }}
