{{- if .Values.backendConfigEnabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.backendConfig.name }}
spec:
  connectionDraining:
    drainingTimeoutSec: {{ .Values.backendConfig.connectionDraining.drainingTimeoutSec | default 0 }}  
  timeoutSec: {{ .Values.backendConfig.timeoutSec | default 30 }}
  {{- if .Values.backendConfig.healthCheckEnabled }}
  healthCheck:
    checkIntervalSec: {{ .Values.backendConfig.healthCheck.checkIntervalSec | default 5 }}
    timeoutSec: {{ .Values.backendConfig.healthCheck.timeoutSec | default 5 }}
    healthyThreshold: {{ .Values.backendConfig.healthCheck.healthyThreshold | default 2 }}
    unhealthyThreshold: {{ .Values.backendConfig.healthCheck.unhealthyThreshold | default 2 }}
    type: {{ .Values.backendConfig.healthCheck.type | default "HTTP" }}
    requestPath: {{ .Values.backendConfig.healthCheck.requestPath | default "/" }}
    port: {{ .Values.backendConfig.healthCheck.port | default 80 }}
  {{- end }}
  {{- if .Values.backendConfig.securityPolicyName }}
  securityPolicy:
    name: {{ .Values.backendConfig.securityPolicyName }}
  {{- end }}
{{- end }}  