angular:
  enabled: true
  replicaCount: 1
  image:
    repository: pranavdhopey/angular-app
    pullPolicy: IfNotPresent
    tag: ""
  labels:
    env: prod   
  serviceAccount:
    create: false
  # fullnameOverride: "angular"
  service:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
react:
  enabled: false
  replicaCount: 1
  image:
    repository: pranavdhopey/react-app
    pullPolicy: IfNotPresent
    tag: ""
  labels:
    env: prod   
  serviceAccount:
    create: false
  # fullnameOverride: "react"
  service:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
nodejs:
  enabled: false
  replicaCount: 1
  image:
    repository: pranavdhopey/nodejs-app
    pullPolicy: IfNotPresent
    tag: ""
  labels:
    env: prod   
  serviceAccount:
    create: false
  # fullnameOverride: "nodejs"
spring:
  enabled: false
  replicaCount: 1
  image:
    repository: pranavdhopey/spring-app
    pullPolicy: IfNotPresent
    tag: ""
  labels:
    env: prod   
  serviceAccount:
    create: false
  # fullnameOverride: "spring"
